# Generated by Django 3.2.16 on 2023-01-16 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-added_on']},
        ),
    ]
